/* Generated By:JavaCC: Do not edit this line. GenerateurAnalyseurTreeConstants.java Version 5.0 */
package cAnalyseur;

public interface GenerateurAnalyseurTreeConstants
{
  public int JJTCONSTANTE = 0;
  public int JJTVARIABLE = 1;
  public int JJTVOID = 2;
  public int JJTALTERNATIVE1 = 3;
  public int JJTALTERNATIVE2 = 4;
  public int JJTRS = 5;
  public int JJTBL = 6;
  public int JJTRG = 7;
  public int JJTMC = 8;
  public int JJTPA = 9;
  public int JJTTU = 10;
  public int JJTRO = 11;
  public int JJTAE = 12;
  public int JJTAO = 13;
  public int JJTAN = 14;
  public int JJTAS = 15;
  public int JJTED = 16;
  public int JJTOD = 17;
  public int JJTND = 18;
  public int JJTSD = 19;
  public int JJTMA = 20;
  public int JJTMO = 21;
  public int JJTEN = 22;
  public int JJTEP = 23;
  public int JJTEG = 24;
  public int JJTEM = 25;
  public int JJTPP = 26;
  public int JJTPG = 27;
  public int JJTMT = 28;
  public int JJTEQ = 29;
  public int JJTFORMULE = 30;
  public int JJTUNARY = 31;
  public int JJTOR = 32;
  public int JJTAD = 33;
  public int JJTNO = 34;
  public int JJTIP = 35;
  public int JJTBP = 36;
  public int JJTQUANTIFICATEUR = 37;
  public int JJTFL = 38;
  public int JJTEX = 39;
  public int JJTOPERATEUR = 40;


  public String[] jjtNodeName = {
    "constante",
    "variable",
    "void",
    "alternative1",
    "alternative2",
    "rs",
    "bl",
    "rg",
    "mc",
    "pa",
    "tu",
    "ro",
    "ae",
    "ao",
    "an",
    "as",
    "ed",
    "od",
    "nd",
    "sd",
    "ma",
    "mo",
    "en",
    "ep",
    "eg",
    "em",
    "pp",
    "pg",
    "mt",
    "eq",
    "FORMULE",
    "UNARY",
    "or",
    "ad",
    "no",
    "ip",
    "bp",
    "quantificateur",
    "fl",
    "ex",
    "OPERATEUR",
  };
}
/* JavaCC - OriginalChecksum=8725ba6e9bc9dd033f8c4a5e2312d9cc (do not edit this line) */
