/* Generated By:JJTree&JavaCC: Do not edit this line. GenerateurAnalyseurConstants.java */
package cAnalyseur;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GenerateurAnalyseurConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANTE = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CONSTANTE>",
    "<VARIABLE>",
    "\"est_rose(\"",
    "\")\"",
    "\"est_blanc(\"",
    "\"est_rouge(\"",
    "\"(\"",
    "\",\"",
    "\"meme_couleur_que\"",
    "\"Paquerette(\"",
    "\"Tulipe(\"",
    "\"Rose(\"",
    "\"a_l_est(\"",
    "\"a_l_ouest(\"",
    "\"au_nord(\"",
    "\"au_sud(\"",
    "\"a_l_est_de\"",
    "\"a_l_ouest_de\"",
    "\"au_nord_de\"",
    "\"au_sud_de\"",
    "\"meme_latitude\"",
    "\"meme_longitude\"",
    "\"est_entre\"",
    "\"est_petit(\"",
    "\"est_grand(\"",
    "\"est_moyen(\"",
    "\"plus_petit_que\"",
    "\"plus_grand_que\"",
    "\"meme_taille_que\"",
    "\"=\"",
    "\"V\"",
    "\"\\u2227\"",
    "\"\\u00ac\"",
    "\"\\u21d2\"",
    "\"<=>\"",
    "\"\\u2200\"",
    "\"\\u2203\"",
  };

}
