/* Generated By:JavaCC: Do not edit this line. GenerateurAnalyseurTreeConstants.java Version 5.0 */
package cAnalyseur;

public interface GenerateurAnalyseurTreeConstants
{
  public int JJTCONSTANTE = 0;
  public int JJTVARIABLE = 1;
  public int JJTVOID = 2;
  public int JJTALTERNATIVE1 = 3;
  public int JJTALTERNATIVE2 = 4;
  public int JJTEST_ROSE = 5;
  public int JJTEST_BLANCHE = 6;
  public int JJTEST_ROUGE = 7;
  public int JJTMM_COL_QUE = 8;
  public int JJTPAQUERETTE = 9;
  public int JJTTULIPE = 10;
  public int JJTROSE = 11;
  public int JJTAT_EST = 12;
  public int JJTAT_OUEST = 13;
  public int JJTAT_NORD = 14;
  public int JJTAT_SUD = 15;
  public int JJTAT_EST_DE = 16;
  public int JJTAT_OUEST_DE = 17;
  public int JJTAT_NORD_DE = 18;
  public int JJTAT_SUD_DE = 19;
  public int JJTMM_LATITUDE = 20;
  public int JJTMM_LONGITUDE = 21;
  public int JJTEST_ENTRE = 22;
  public int JJTEST_PETIT = 23;
  public int JJTEST_GRAND = 24;
  public int JJTEST_MOYEN = 25;
  public int JJTPLUS_PETIT_QUE = 26;
  public int JJTPLUS_GRAND_QUE = 27;
  public int JJTMM_TAILLE = 28;
  public int JJTEST_EGAL = 29;
  public int JJTUNARY = 30;
  public int JJTOR = 31;
  public int JJTAND = 32;
  public int JJTNOT = 33;
  public int JJTIMPLIES = 34;
  public int JJTBIMPLIES = 35;
  public int JJTFORALL = 36;
  public int JJTEXISTS = 37;
  public int JJTOPERATEUR = 38;


  public String[] jjtNodeName = {
    "constante",
    "variable",
    "void",
    "alternative1",
    "alternative2",
    "EST_ROSE",
    "EST_BLANCHE",
    "EST_ROUGE",
    "MM_COL_QUE",
    "PAQUERETTE",
    "TULIPE",
    "ROSE",
    "AT_EST",
    "AT_OUEST",
    "AT_NORD",
    "AT_SUD",
    "AT_EST_DE",
    "AT_OUEST_DE",
    "AT_NORD_DE",
    "AT_SUD_DE",
    "MM_LATITUDE",
    "MM_LONGITUDE",
    "EST_ENTRE",
    "EST_PETIT",
    "EST_GRAND",
    "EST_MOYEN",
    "PLUS_PETIT_QUE",
    "PLUS_GRAND_QUE",
    "MM_TAILLE",
    "EST_EGAL",
    "UNARY",
    "OR",
    "AND",
    "NOT",
    "IMPLIES",
    "BIMPLIES",
    "FORALL",
    "EXISTS",
    "OPERATEUR",
  };
}
/* JavaCC - OriginalChecksum=22d1b8f82558d5a27ed288120593c5ed (do not edit this line) */
